### ISSUE TITLE
Bug:FullAuto mod allows sprinting and shooting with Laspistol

### ISSUE THREAD

**Issue by gpkgpk** [ItsAlxl/darktide-mods#34]
Bug: FullAuto mod allows sprinting and shooting with Laspistol

**Comment by ItsAlxl** [comment]
In general, I prefer bug reports on the specific mod's Nexus page directly. It's just a bit easier for me to keep track of & helps other people see which bugs are known and to see which version contains fixes.

That said, this is actually not a bug! You can shoot the laspistol while shooting in the vanilla game, but if you spam click it'll cancel the sprint. Older versions of FullAuto would similarly cancel the sprint, until someone told me about sprint-shooting the laspistol, which I previously didn't know about. So then I actually put a pretty significant amount of work in to make sure that the mod will fire the laspistol as fast as it's allowed to while sprinting. So for once, I can honestly say that it's not a bug, it's a feature :)

**Comment by gpkgpk** [comment]
Thanks for the reply and your mods.
Yeah I saw (glanced) in the LUA the laspistol had some interesting stuff attached to it, but this "perfect fire rate while sprinting" feature seems a bit off to me, like it's crossing the line from QoL mod to something else.
It seems the modded sprint RoF is higher (20%?) than what a human can reasonably ever or consistently achieve, not to mention no interruptions.
It doesn't pass the smell test to me, maybe I'm overly sensitive to these things.

P.S. I'll post on Nexus in the future.
